# Generated by Django 4.2.1 on 2023-05-30 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dolgozat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('suly', models.IntegerField(default=100)),
                ('megirasnapja', models.DateField(blank=True, null=True)),
                ('csoport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Dolgozat',
                'verbose_name_plural': 'Dolgozatok',
            },
        ),
        migrations.CreateModel(
            name='UserAdatok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felev', models.IntegerField(blank=True, null=True)),
                ('evvege', models.IntegerField(blank=True, null=True)),
                ('pirosPontok', models.IntegerField(default=0)),
                ('feketePontok', models.IntegerField(default=0)),
                ('csoport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserAdat',
                'verbose_name_plural': 'UserAdatok',
            },
        ),
        migrations.CreateModel(
            name='Tanit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csoport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('tanar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tanár-Csoport reláció',
                'verbose_name_plural': 'Tanár-Csoport relációk',
            },
        ),
        migrations.CreateModel(
            name='Jegy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('suly', models.IntegerField(default=100)),
                ('ertek', models.IntegerField(default=100)),
                ('datum', models.DateField()),
                ('dolgozat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_angol_ertekeles.dolgozat')),
                ('tanulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jegy',
                'verbose_name_plural': 'Jegyek',
            },
        ),
    ]
