# Generated by Django 4.2.1 on 2023-06-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_angol_ertekeles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradatok',
            name='csoport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
