# Generated by Django 4.2.1 on 2023-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_angol_ertekeles', '0002_alter_useradatok_csoport'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanit',
            name='maxfeketepont',
            field=models.IntegerField(default=4, max_length=2),
        ),
        migrations.AddField(
            model_name='tanit',
            name='maxpirospont',
            field=models.IntegerField(default=4, max_length=2),
        ),
    ]
