# Generated by Django 4.2.1 on 2023-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_angol_ertekeles', '0003_tanit_maxfeketepont_tanit_maxpirospont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanit',
            name='maxfeketepont',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='tanit',
            name='maxpirospont',
            field=models.IntegerField(default=4),
        ),
    ]
